apiVersion: batch/v1
kind: Job
metadata:
  name: message-sender
  namespace: messaging-pipeline
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sender
        image: natsio/nats-box:latest
        command: ["nats"]
        args:
        - "pub"
        - "app1.input"
        - '{"message": "hello, world"}'
        - "--server=nats-service:4222"
